language: objective-c

env:
  global:
  - HXCPP_COMPILE_CACHE=~/hxcache

os: osx

osx_image: xcode12.2

cache:
  directories:
  - $HXCPP_COMPILE_CACHE

before_install:
- wget -c https://github.com/HaxeFoundation/neko/releases/download/v2-3-0/neko-2.3.0-osx64.tar.gz
- sudo mkdir /usr/local/lib/neko
- sudo tar xvzf neko-2.3.0-osx64.tar.gz -C /usr/local/lib/neko
- sudo ln -s /usr/local/lib/neko/neko /usr/local/bin/neko
- sudo ln -s /usr/local/lib/neko/libneko.2.3.0.dylib /usr/local/lib/libneko.2.dylib
- sudo ln -s /usr/local/lib/neko/libneko.2.3.0.dylib /usr/local/lib/libneko.dylib
- sudo ln -s /usr/local/lib/neko/libneko.2.3.0.dylib /usr/local/lib/neko/libneko.2.dylib
- sudo ln -s /usr/local/lib/neko/libneko.2.3.0.dylib /usr/local/lib/neko/libneko.dylib
- sudo ln -s /usr/local/lib/neko/libneko.2.3.0.dylib /usr/local/bin/libneko.2.dylib
- sudo ln -s /usr/local/lib/neko/libneko.2.3.0.dylib /usr/local/bin/libneko.dylib
- find /usr/local -name libneko.2.dylib
- wget -c https://github.com/HaxeFoundation/haxe/releases/download/4.1.4/haxe-4.1.4-osx.tar.gz
- sudo mkdir /usr/local/lib/haxe
- sudo tar xvzf haxe-4.1.4-osx.tar.gz -C /usr/local/lib/haxe --strip-components=1
- sudo ln -s /usr/local/lib/haxe/haxe /usr/local/bin/haxe
- sudo ln -s /usr/local/lib/haxe/haxelib /usr/local/bin/haxelib
- mkdir ~/haxelib
- export DYLD_PRINT_RPATHS=1
- export DYLD_PRINT_APIS=1
- haxelib setup ~/haxelib
- haxelib dev nme $(pwd)
- git clone https://github.com/HaxeFoundation/hxcpp ~/hxcpp --depth 1
- haxelib dev hxcpp ~/hxcpp
- cd ~/hxcpp/tools/hxcpp
- haxe compile.hxml
- cd ~/hxcpp/tools/run
- haxe compile.hxml
- haxelib -notimeout install nme-toolkit
- haxelib -notimeout install format
- haxelib -notimeout install gm2d

script:
- cd $TRAVIS_BUILD_DIR/tools/nme
- haxe compile.hxml
- cd $TRAVIS_BUILD_DIR/project
- neko build.n
- cd $TRAVIS_BUILD_DIR/tools/nme
- haxelib run nme setup
- haxe test.hxml
- neko bin/TestMain.n
- cd $TRAVIS_BUILD_DIR/tests
- haxe -x RunAll
- cd $TRAVIS_BUILD_DIR/tests/haxe
- haxe compile.hxml
- bin/TestMain
